### ISSUE TITLE
Canvas page

### ISSUE THREAD

**Issue by hhkimmm9** [hhkimmm9/NATechPro1#19]
## Libraries
[Fabric.js](http://fabricjs.com/)
[drag and drop](https://g4sc2.csb.app/)
React dropzone
jQueryUI and KineticJS

[google docs 참조](https://docs.google.com/document/d/1VSpjK3jBItK1ob2Fdg20xCPBalMYhQCOAMm2FhyAVGU/edit#)

## Tasks
- [ ] frontend layout
- [ ] react-dropzone 통해서 upload new background 하면 backend/cloudinary 에 보내주기
  - 파일 업로드하면 올린 샘플 이미지를 다시 유저한테 보여줘야 함.
- [ ] image holder 에 gallery 에 있는 이미지 담아둘 수 있어야 함
  - /api/gallery? (name/tags) 로 이미지 불러오는거 가능
- [ ] image holder 에 잇는 이미지를 캔버스로 끌고 오기 위해서 react-knova 사용 예정
- [ ] toolbox 에 이미지 편집 툴은 fabric.js?
- [ ] 최종적으로 save 누르면 다시 서버에 편집한 이미지 보내서 갤러리에서 확인할 수 있게끔
