### ISSUE TITLE
next-auth backend token management in DB

### ISSUE THREAD

**Issue by hhkimmm9** [hhkimmm9/NATechPro1#32]
## Tasks
- [x] store user data; token, into our DB
    - [x] mongoDB 
- [x] Access Token
- [ ] Refresh Token
- [x] Redirect with Callback URL
- [x] Protected Route using Next-Auth Middleware

## Follow-up
토큰 작업 완료 후에 갤러리 백앤드에서 토큰 기능 추가해주시면 됩니다
- #34

**Comment by hhkimmm9** [comment]
토큰을 DB 에 저장하는게 아니라 cookie 에 저장하는 방법을 사용하기로 했습니다.
