### ISSUE TITLE
Gallery CRUD Ops

### ISSUE THREAD

**Issue by hhkimmm9** [hhkimmm9/NATechPro1#5]
## Tasks
- [x] 에디터 페이지에서 서버로 보낸 이미지를 갤러리에 저장할 수 있어야 합니다.
- [x] 갤러리 페이지에서 로그인한 유저가 저장한 이미지를 모두 불러올 수 있어야 합니다.
  - 추후 filtering, sorting, search by title/tag 등 기능이 추가될 예정입니다.
- [x] (보류) 이미지 서버 선택
  - [cloudinary](https://cloudinary.com/ip/gr-sea-gg-brand-home-base?utm_source=google&utm_medium=search&utm_campaign=goog_selfserve_brand_wk22_replicate_core_branded_keyword&utm_term=1329&campaignid=18164753405&adgroupid=144188713167&keyword=cloudinary&device=c&matchtype=e&adposition=&gad=1&gclid=Cj0KCQjwmN2iBhCrARIsAG_G2i7Q2PgEbqbPgAj5vv6OMYt3NxCkJiUGry3pe2CKuB2JAJc-7MBzGKYaAp2LEALw_wcB)

## Attributes
- File path
- Image size
- ...
