### ISSUE TITLE
Tags API

### ISSUE THREAD

**Issue by hhkimmm9** [hhkimmm9/NATechPro1#6]
## Tasks
- [x] Create 'tags' document
- [x] Add certain attributes (label, user_id, image_id, theme?)
- [x] create, update, delete
